import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kyle Conrad - Design Technologist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full h-full m-0 p-0">
      <head>
        <title>Kyle Conrad - Design Technologist</title>
        <link rel="stylesheet" href="https://use.typekit.net/nxc3ejx.css" />
      </head>
      <body className="w-full h-full flex flex-col">{children}</body>
    </html>
  );
}
